version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tippy.js
    versions:
    - 6.2.7
    - 6.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
